language: r
pandoc_version: 1.17.2
cache: packages

script:
  - Rscript -e "blogdown::install_hugo(version = \"0.19\")"
  - Rscript -e "blogdown::build_site()"
  - ./_deploy.sh

after_success:
  - chmod +x ./_deploy.sh
