language: r
pandoc_version: 1.17.2
cache: packages

script:
  - Rscript -e "blogdown::install_hugo()"
  - Rscript -e "blogdown::build_site()"
  - ./_deploy.sh

before_script:
  - chmod +x ./_deploy.sh
